import { User, Training } from '@/types';

export const mockUser: User = {
  id: 'user-1',
  email: 'kimsarang@school.go.kr',
  full_name: '김사랑',
  position: '교사',
  is_admin: false,
  created_at: '2023-03-15',
};

export const mockAdminUser: User = {
  id: 'admin-1',
  email: 'kimjimin@school.go.kr',
  full_name: '김지민',
  position: '교사',
  is_admin: true,
  created_at: '2023-01-10',
};

export const mockTrainings: Training[] = [
  {
    id: 't1',
    user_id: 'user-1',
    training_name: '고급 교실 관리 전략',
    institution_name: '교육청',
    training_type: '직무(대면)',
    start_date: '2023-10-10',
    end_date: '2023-10-12',
    hours: 15,
    is_paid: false,
    fee: null,
    certificate_url: null,
    status: '완료',
    category: '전문성 개발',
    created_at: '2023-10-12',
    updated_at: '2023-10-12',
  },
  {
    id: 't2',
    user_id: 'user-1',
    training_name: 'STEM 교육의 디지털 리터라시',
    institution_name: '테크에듀 아카데미',
    training_type: '직무(집합)',
    start_date: '2023-11-01',
    end_date: '2023-11-05',
    hours: 12.5,
    is_paid: true,
    fee: 150000,
    certificate_url: null,
    status: '승인 대기',
    category: '기술 워크숍',
    created_at: '2023-11-05',
    updated_at: '2023-11-05',
  },
  {
    id: 't3',
    user_id: 'user-1',
    training_name: '포용적 교육 전략',
    institution_name: '글로벌 스쿨 이니셔티브',
    training_type: '직무(원격)',
    start_date: '2023-09-25',
    end_date: '2023-09-28',
    hours: 8,
    is_paid: false,
    fee: null,
    certificate_url: null,
    status: '완료',
    category: '다양성 및 포용성',
    created_at: '2023-09-28',
    updated_at: '2023-09-28',
  },
  {
    id: 't4',
    user_id: 'user-1',
    training_name: '학생 심리학 기초',
    institution_name: '중앙대학교',
    training_type: '직무(원격)',
    start_date: '2023-08-10',
    end_date: '2023-08-14',
    hours: 6,
    is_paid: true,
    fee: 80000,
    certificate_url: null,
    status: '반려',
    category: '상담 선택과목',
    created_at: '2023-08-14',
    updated_at: '2023-08-14',
  },
  {
    id: 't5',
    user_id: 'user-1',
    training_name: '법정의무연수 묶음과정',
    institution_name: '서울특별시교육청연수원',
    training_type: '직무(원격)',
    start_date: '2023-07-01',
    end_date: '2023-07-03',
    hours: 7,
    is_paid: false,
    fee: null,
    certificate_url: null,
    status: '완료',
    created_at: '2023-07-03',
    updated_at: '2023-07-03',
  },
];

export const mockAllTrainings: Training[] = [
  ...mockTrainings.map(t => ({ ...t, user_name: '김사랑', user_position: '교사' })),
  {
    id: 't6',
    user_id: 'user-2',
    training_name: '수학 교육과정 심화',
    institution_name: '중앙교육연수원',
    training_type: '직무(원격)',
    start_date: '2023-09-01',
    end_date: '2023-09-15',
    hours: 30,
    is_paid: false,
    fee: null,
    certificate_url: null,
    status: '완료',
    created_at: '2023-09-15',
    updated_at: '2023-09-15',
    user_name: '제임스 윌슨',
    user_position: '수석 교사 (수학)',
  },
  {
    id: 't7',
    user_id: 'user-3',
    training_name: '과학 실험 안전 교육',
    institution_name: '한국교육학술정보원',
    training_type: '직무(대면)',
    start_date: '2023-10-05',
    end_date: '2023-10-06',
    hours: 12,
    is_paid: false,
    fee: null,
    certificate_url: null,
    status: '완료',
    created_at: '2023-10-06',
    updated_at: '2023-10-06',
    user_name: '엘레나 로드리게스',
    user_position: '일반 교사 (과학)',
  },
  {
    id: 't8',
    user_id: 'user-4',
    training_name: '디지털 안전',
    institution_name: '한국교육과정평가원',
    training_type: '직무(집합)',
    start_date: '2023-11-10',
    end_date: '2023-11-20',
    hours: 50,
    is_paid: true,
    fee: 200000,
    certificate_url: null,
    status: '완료',
    created_at: '2023-11-20',
    updated_at: '2023-11-20',
    user_name: '마이클 장',
    user_position: '체육 강사',
  },
  {
    id: 't9',
    user_id: 'user-5',
    training_name: '영어 수업 방법론',
    institution_name: '티처빌원격교육연수원',
    training_type: '직무(원격)',
    start_date: '2023-08-20',
    end_date: '2023-09-10',
    hours: 34,
    is_paid: false,
    fee: null,
    certificate_url: null,
    status: '완료',
    created_at: '2023-09-10',
    updated_at: '2023-09-10',
    user_name: '사라 밀러',
    user_position: '일반 교사 (영어)',
  },
];

export const mockTeacherSummaries = [
  {
    id: 'user-2',
    name: '제임스 윌슨',
    position: '수석 교사 (수학)',
    email: 'james@school.go.kr',
    totalTrainings: 8,
    totalHours: 42.5,
    achievementRate: 85,
  },
  {
    id: 'user-3',
    name: '엘레나 로드리게스',
    position: '일반 교사 (과학)',
    email: 'elena@school.go.kr',
    totalTrainings: 4,
    totalHours: 12.0,
    achievementRate: 30,
  },
  {
    id: 'user-4',
    name: '마이클 장',
    position: '체육 강사',
    email: 'michael@school.go.kr',
    totalTrainings: 10,
    totalHours: 50.0,
    achievementRate: 100,
  },
  {
    id: 'user-5',
    name: '사라 밀러',
    position: '일반 교사 (영어)',
    email: 'sarah@school.go.kr',
    totalTrainings: 6,
    totalHours: 34.0,
    achievementRate: 68,
  },
];
